### PR TITLE
github workflows added

### LINKED ISSUE #20: Adding auto commenting option
adding auto commenting on PR merge and issue creation . please assign me under wob24

### PR DESCRIPTION
**Pull request by dhairyagothi**
**Summary:**  
Provide a brief overview of the changes introduced in this PR.
Added autocommenting option on PR merge and issue creation issue close 
closes #20 

**Changes Made:**  
Describe the changes you made and why they were necessary.

**Testing Performed:**  
- [x] I have tested my changes to ensure they work as expected.  
- [x] I have followed the contribution guidelines.  
- [x] I have named my commit message(s) in accordance with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).

**Related Issues:**  
Link any related issues or tickets that this PR addresses.

**Additional Notes:**  
Any additional information or context about this PR.

### CODE REVIEW

**Comment by dhairyagothi** [comment]
@Krishi1211 please add WBOC label and level label also

**Comment by dhairyagothi** [comment]
@Sanskriti1102 please add hacktoberfest label

**Comment by Krishi1211** [comment]
@dhairyagothi This project isnt under hacktober fest
And i have added wob label in the issue that you have created

**Comment by dhairyagothi** [comment]
> @dhairyagothi This project isnt under hacktober fest
> And i have added wob label in the issue that you have created

I am also PA in GSSOC'24 EXTENDED 

I recently noticed that wob is merged with gssoc and this is under gssoc'24 EXTENDED now . 

Second thing contribution score will be counted when Labels are present on PR

**Pull request merged**
